apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-apps
  namespace: telemetry
  labels:
    app: otel-collector-apps
spec:
  selector:
    matchLabels:
      app: otel-collector-apps
  template:
    metadata:
      labels:
        app: otel-collector-apps
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8889"
    spec:
      serviceAccountName: otel-collector-apps
      containers:
      - name: otel-collector-apps
        image: otel/opentelemetry-collector-contrib:0.128.0
        env:
        - name: KUBE_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - "--config=/etc/otel-collector.yaml"
        ports:
        - containerPort: 4317
          hostPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otlp-http
        - containerPort: 8889
          name: prometheus
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otel-collector.yaml
          subPath: collector-config.yaml
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: otel-collector-config
        configMap:
          name: collector-config-apps
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: Exists